### ISSUE TITLE
Class-balanced sampling的一点疑惑

### ISSUE THREAD

**Issue by ljjcoder** [lslrh/CPSL#5]
您好，从您定义的公式（9）来看，每个类别采样的像素值是根据伪标签中各个类别占比确定的，因此M中的各个类别的像素个数还是不平衡的。请问这种采样方式为什么能解决长尾为题？

**Comment by lslrh** [comment]
Thanks for your interest. Class balance means we sample from different classes by the same proportion, which ensures that all classes of pixels can be sampled, so that the class distribution of pixels in the memory bank  is close to that of the whole dataset. Then by enforcing the constraint in Eq.12, we could avoid the model from being biased to the majority categories in training process.

**Comment by StuLiu** [comment]
请问采样符合真实分布为何能解决长尾问题？
